In [1]:
# Import required libraries
import nltk
from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords
from nltk.stem import PorterStemmer, WordNetLemmatizer
from nltk import pos_tag
from sklearn.feature_extraction.text import TfidfVectorizer

# Download necessary datasets (run only once)
nltk.download('punkt')
nltk.download('stopwords')
nltk.download('averaged_perceptron_tagger')
nltk.download('wordnet')

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.
[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.
[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     /root/nltk_data...
[nltk_data]   Unzipping taggers/averaged_perceptron_tagger.zip.
[nltk_data] Downloading package wordnet to /root/nltk_data...

True

In [2]:
# Load the given text files
with open("PRINCIPALS_MESSAGE.txt", "r", encoding="utf-8") as f:
    doc1 = f.read()

with open("DIRECTORS_MESSAGE.txt", "r", encoding="utf-8") as f:
    doc2 = f.read()

# Combine documents into a list
documents = [doc1, doc2]

print("Documents Loaded Successfully!")

Documents Loaded Successfully!

In [3]:
print("Document 1 Sample:\n", doc1[:200])
print("\nDocument 2 Sample:\n", doc2[:200])

Document 1 Sample:
 It gives me immense pleasure in welcoming you to SCTR’s Pune Institute of Computer Technology, a premier and a very reputed institute. Pune Institute of Computer Technology, popularly known as PICT, w

Document 2 Sample:
 Pune Institute of Computer Technology (PICT) was established in 1983 by a group of enterprising visionary professionals and has come a long way and marched ahead with quality education imbibed with pr

In [5]:
#tokenization break text into smaller part
nltk.download('punkt_tab')
token_doc1 = word_tokenize(doc1);
token_doc2 = word_tokenize(doc2);

print('\nDoc1 tokens:')
print(token_doc1[:40])
print('\nDoc2 tokens:')
print(token_doc2[:40])

[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt_tab.zip.

Doc1 tokens:
['It', 'gives', 'me', 'immense', 'pleasure', 'in', 'welcoming', 'you', 'to', 'SCTR', '’', 's', 'Pune', 'Institute', 'of', 'Computer', 'Technology', ',', 'a', 'premier', 'and', 'a', 'very', 'reputed', 'institute', '.', 'Pune', 'Institute', 'of', 'Computer', 'Technology', ',', 'popularly', 'known', 'as', 'PICT', ',', 'was', 'established', 'in']

Doc2 tokens:
['Pune', 'Institute', 'of', 'Computer', 'Technology', '(', 'PICT', ')', 'was', 'established', 'in', '1983', 'by', 'a', 'group', 'of', 'enterprising', 'visionary', 'professionals', 'and', 'has', 'come', 'a', 'long', 'way', 'and', 'marched', 'ahead', 'with', 'quality', 'education', 'imbibed', 'with', 'professional', 'and', 'ethical', 'values', '.', 'Our', 'mission']

In [8]:
#assign grammtical label like noun, preposition,verb
nltk.download('averaged_perceptron_tagger_eng')
pos_tags1 = pos_tag(token_doc1)
pos_tags2 = pos_tag(token_doc2)

print("\nPOS Tags1:")
print(pos_tags1[:50])

print("\nPOS Tags2:")
print(pos_tags2[:50])

[nltk_data] Downloading package averaged_perceptron_tagger_eng to
[nltk_data]     /root/nltk_data...
[nltk_data]   Unzipping taggers/averaged_perceptron_tagger_eng.zip.

POS Tags1:
[('It', 'PRP'), ('gives', 'VBZ'), ('me', 'PRP'), ('immense', 'JJ'), ('pleasure', 'NN'), ('in', 'IN'), ('welcoming', 'VBG'), ('you', 'PRP'), ('to', 'TO'), ('SCTR', 'NNP'), ('’', 'NNP'), ('s', 'VBD'), ('Pune', 'NNP'), ('Institute', 'NNP'), ('of', 'IN'), ('Computer', 'NNP'), ('Technology', 'NNP'), (',', ','), ('a', 'DT'), ('premier', 'NN'), ('and', 'CC'), ('a', 'DT'), ('very', 'RB'), ('reputed', 'JJ'), ('institute', 'NN'), ('.', '.'), ('Pune', 'NNP'), ('Institute', 'NNP'), ('of', 'IN'), ('Computer', 'NNP'), ('Technology', 'NNP'), (',', ','), ('popularly', 'RB'), ('known', 'VBN'), ('as', 'IN'), ('PICT', 'NNP'), (',', ','), ('was', 'VBD'), ('established', 'VBN'), ('in', 'IN'), ('1983', 'CD'), (',', ','), ('by', 'IN'), ('a', 'DT'), ('group', 'NN'), ('of', 'IN'), ('great', 'JJ'), ('visionaries', 'NNS'), (',', ','), ('Late', 'NNP')]

POS Tags2:
[('Pune', 'NNP'), ('Institute', 'NNP'), ('of', 'IN'), ('Computer', 'NNP'), ('Technology', 'NNP'), ('(', '('), ('PICT', 'NNP'), (')', ')'), ('was', 'VBD'), ('established', 'VBN'), ('in', 'IN'), ('1983', 'CD'), ('by', 'IN'), ('a', 'DT'), ('group', 'NN'), ('of', 'IN'), ('enterprising', 'VBG'), ('visionary', 'JJ'), ('professionals', 'NNS'), ('and', 'CC'), ('has', 'VBZ'), ('come', 'VBN'), ('a', 'DT'), ('long', 'JJ'), ('way', 'NN'), ('and', 'CC'), ('marched', 'VBD'), ('ahead', 'RB'), ('with', 'IN'), ('quality', 'JJ'), ('education', 'NN'), ('imbibed', 'VBN'), ('with', 'IN'), ('professional', 'JJ'), ('and', 'CC'), ('ethical', 'JJ'), ('values', 'NNS'), ('.', '.'), ('Our', 'PRP$'), ('mission', 'NN'), ('is', 'VBZ'), ('to', 'TO'), ('be', 'VB'), ('the', 'DT'), ('most', 'RBS'), ('sought-after', 'JJ'), ('institute', 'NN'), ('in', 'IN'), ('Engineering', 'NNP'), ('education', 'NN')]

In [9]:
#stop word removal words like in, a, the ,as not required
stop_words = set(stopwords.words('english'))
new_token1 = [word for word in token_doc1 if word.lower() not in stop_words]
new_token2 = [word for word in token_doc2 if word.lower() not in stop_words]

print("\nAfter Stop Word Removal1:")
print(new_token1[:50])

print("\nAfter Stop Word Removal2:")
print(new_token2[:50])

After Stop Word Removal1:
['gives', 'immense', 'pleasure', 'welcoming', 'SCTR', '’', 'Pune', 'Institute', 'Computer', 'Technology', ',', 'premier', 'reputed', 'institute', '.', 'Pune', 'Institute', 'Computer', 'Technology', ',', 'popularly', 'known', 'PICT', ',', 'established', '1983', ',', 'group', 'great', 'visionaries', ',', 'Late', 'Mr.', 'Dr.', 'N.', 'Gopalkrishnan', ',', 'Mr.', 'N.', 'Rama', 'Krishnan', 'Managing', 'Trustee', 'Mr.', 'Rajkumar', 'Kothavale', '.', 'ingenious', 'founder', 'team']

After Stop Word Removal2:
['Pune', 'Institute', 'Computer', 'Technology', '(', 'PICT', ')', 'established', '1983', 'group', 'enterprising', 'visionary', 'professionals', 'come', 'long', 'way', 'marched', 'ahead', 'quality', 'education', 'imbibed', 'professional', 'ethical', 'values', '.', 'mission', 'sought-after', 'institute', 'Engineering', 'education', 'research', ',', 'provides', 'relevant', 'knowledge', ',', 'creates', 'challenging', 'opportunities', ',', 'inculcate', 'values', 'social', 'responsibilities', '.', 'Pune', 'Institute', 'Computer', 'Technology', 'cut']

In [10]:
#stemming reduce to original or root form
#removes suffix like ing, ed, ly, is
stemmer = PorterStemmer()

stemmed_word1 = [stemmer.stem(word) for word in new_token1]
stenned_word2 = [stemmer.stem(word) for word in new_token2]

print("\nStemmed Words1:")
print(stemmed_word1[:50])

print("\nStemmed Words2:")
print(stenned_word2[:50])

Stemmed Words1:
['give', 'immens', 'pleasur', 'welcom', 'sctr', '’', 'pune', 'institut', 'comput', 'technolog', ',', 'premier', 'reput', 'institut', '.', 'pune', 'institut', 'comput', 'technolog', ',', 'popularli', 'known', 'pict', ',', 'establish', '1983', ',', 'group', 'great', 'visionari', ',', 'late', 'mr.', 'dr.', 'n.', 'gopalkrishnan', ',', 'mr.', 'n.', 'rama', 'krishnan', 'manag', 'truste', 'mr.', 'rajkumar', 'kothaval', '.', 'ingeni', 'founder', 'team']

Stemmed Words2:
['pune', 'institut', 'comput', 'technolog', '(', 'pict', ')', 'establish', '1983', 'group', 'enterpris', 'visionari', 'profession', 'come', 'long', 'way', 'march', 'ahead', 'qualiti', 'educ', 'imbib', 'profession', 'ethic', 'valu', '.', 'mission', 'sought-aft', 'institut', 'engin', 'educ', 'research', ',', 'provid', 'relev', 'knowledg', ',', 'creat', 'challeng', 'opportun', ',', 'inculc', 'valu', 'social', 'respons', '.', 'pune', 'institut', 'comput', 'technolog', 'cut']

In [11]:
#lemmatization means reduce word to base or dictionary form
#better good, rocks rock
# Lemmatization
lemmatizer = WordNetLemmatizer()

lemmatized_words1 = [lemmatizer.lemmatize(word) for word in new_token1]
lemmatized_words2 = [lemmatizer.lemmatize(word) for word in new_token2]

print("\nLemmatized Words1:")
print(lemmatized_words1[:50])

print("\nLemmatized Words2:")
print(lemmatized_words2[:50])

Lemmatized Words1:
['give', 'immense', 'pleasure', 'welcoming', 'SCTR', '’', 'Pune', 'Institute', 'Computer', 'Technology', ',', 'premier', 'reputed', 'institute', '.', 'Pune', 'Institute', 'Computer', 'Technology', ',', 'popularly', 'known', 'PICT', ',', 'established', '1983', ',', 'group', 'great', 'visionary', ',', 'Late', 'Mr.', 'Dr.', 'N.', 'Gopalkrishnan', ',', 'Mr.', 'N.', 'Rama', 'Krishnan', 'Managing', 'Trustee', 'Mr.', 'Rajkumar', 'Kothavale', '.', 'ingenious', 'founder', 'team']

Lemmatized Words2:
['Pune', 'Institute', 'Computer', 'Technology', '(', 'PICT', ')', 'established', '1983', 'group', 'enterprising', 'visionary', 'professional', 'come', 'long', 'way', 'marched', 'ahead', 'quality', 'education', 'imbibed', 'professional', 'ethical', 'value', '.', 'mission', 'sought-after', 'institute', 'Engineering', 'education', 'research', ',', 'provides', 'relevant', 'knowledge', ',', 'creates', 'challenging', 'opportunity', ',', 'inculcate', 'value', 'social', 'responsibility', '.', 'Pune', 'Institute', 'Computer', 'Technology', 'cut']

In [12]:
#TF-IDF term frequency, inverse document frequency
#TF : How many times a word occurs
#IDF : how unique a word is
#TF(t,d)=Total number of terms in document d/ Number of times term t appears in document d​
#IDF(t,d)=log(N/DF(t))

documents = [doc1, doc2]

vectorizer = TfidfVectorizer(stop_words='english')

tfidf_matrix = vectorizer.fit_transform(documents)

feature_names = vectorizer.get_feature_names_out()

In [13]:
import numpy as np
np.set_printoptions(threshold=np.inf)
print("\nFeatures Words: \n", feature_names)
print("\nTF-IDF Matrix: \n", tfidf_matrix.toarray())

Features Words:
 ['10' '100' '12' '19' '1983' '1st' '2015' '240' '326' '3500' '41' '9001'
 'academia' 'academic' 'accomplishments' 'accreditation' 'accredited'
 'achievements' 'achievers' 'achieving' 'acm' 'actively' 'activities'
 'acumen' 'adapting' 'additionally' 'affiliated' 'agencies' 'ahead'
 'aicte' 'alongside' 'ambassadors' 'ambitions' 'annual' 'appreciate'
 'aptitudes' 'art' 'aspiring' 'assessment' 'assure' 'atmosphere'
 'attitude' 'attitudes' 'automobile' 'avenues' 'average' 'awards' 'bagged'
 'based' 'beginning' 'best' 'better' 'betterment' 'big' 'board' 'brand'
 'bridge' 'bright' 'buddy' 'buddys' 'building' 'campus' 'career'
 'carnivals' 'cart' 'caters' 'ce' 'celebrate' 'cell' 'center' 'centered'
 'centres' 'certified' 'challenges' 'challenging' 'chosen' 'circle'
 'close' 'clubs' 'college' 'colleges' 'combination' 'come' 'commendable'
 'committed' 'communication' 'community' 'companies' 'competition'
 'competitiveness' 'computer' 'concepts' 'confident' 'consistently'
 'constant' 'constitute' 'consultancy' 'continue' 'continuous'
 'contributing' 'council' 'country' 'course' 'covid' 'create' 'creates'
 'creativity' 'critical' 'crore' 'csi' 'cultural' 'culture' 'cup'
 'current' 'curricular' 'cut' 'dance' 'data' 'dear' 'debate' 'decades'
 'dedicated' 'demands' 'department' 'desirous' 'despite' 'development'
 'directed' 'director' 'disruption' 'distinction' 'distinctions' 'diverse'
 'dr' 'drama' 'drdo' 'dream' 'dreams' 'drive' 'drives' 'drone' 'dst' 'dte'
 'ecosystem' 'edc' 'educate' 'education' 'efforts' 'electric'
 'electronics' 'empower' 'encourages' 'engineer' 'engineering' 'engineers'
 'ensures' 'entering' 'enterprising' 'entire' 'entrepreneurial'
 'entrepreneurship' 'environment' 'equal' 'equip' 'equipped' 'established'
 'ethical' 'ethics' 'event' 'events' 'examination' 'excel' 'excellence'
 'excellent' 'exciting' 'expand' 'experience' 'experienced' 'exposure'
 'extend' 'extends' 'extra' 'extraordinary' 'faculty' 'fairs' 'family'
 'fe' 'fetched' 'field' 'fierce' 'final' 'finally' 'finding' 'firodiya'
 'flagship' 'focused' 'founder' 'fraternity' 'friends' 'funded' 'funding'
 'future' 'gap' 'getting' 'gives' 'going' 'gopalkrishnan' 'got' 'graded'
 'graduate' 'grants' 'great' 'green' 'group' 'groups' 'growth'
 'hackathons' 'hard' 'heartening' 'help' 'helped' 'helping' 'higher'
 'highest' 'holistic' 'houses' 'hub' 'ict' 'ideas' 'ieee' 'iet'
 'illustrious' 'imagine' 'imbibed' 'immense' 'impetus' 'important'
 'include' 'increased' 'inculcate' 'inculcating' 'india' 'individuals'
 'industrial' 'industry' 'information' 'infrastructure' 'ingenious'
 'innovate' 'innovation' 'innovative' 'inspiring' 'institute'
 'institution' 'institutions' 'integral' 'intense' 'interaction'
 'interests' 'international' 'internship' 'introducing' 'involved' 'iso'
 'job' 'journey' 'karandak' 'karman' 'know' 'knowledge' 'known'
 'kothavale' 'krishnan' 'laboratories' 'lakh' 'late' 'lead' 'leaders'
 'leading' 'learning' 'let' 'levels' 'library' 'life' 'lifetime' 'like'
 'limited' 'local' 'long' 'lot' 'lpa' 'maharashtra' 'make' 'makes'
 'management' 'managing' 'marched' 'medals' 'meet' 'members' 'microsoft'
 'minds' 'mission' 'model' 'modern' 'moulding' 'mr' 'multinational' 'mun'
 'naac' 'national' 'nba' 'neglecting' 'new' 'niche' 'normal' 'notch'
 'nourishes' 'number' 'numerous' 'nurture' 'offers' 'online'
 'opportunities' 'opportunity' 'ordinary' 'outstanding' 'overall'
 'package' 'participation' 'partners' 'pass' 'past' 'patents' 'peaceful'
 'peers' 'percentage' 'period' 'periodic' 'person' 'phule' 'pict'
 'pioneer' 'pioneering' 'placement' 'pleasure' 'popularly' 'position'
 'post' 'potential' 'preferred' 'premier' 'preparing' 'prestigious'
 'pride' 'prizes' 'product' 'profession' 'professional' 'professionalism'
 'professionals' 'professors' 'program' 'programmes' 'programs' 'projects'
 'promotive' 'provide' 'provides' 'providing' 'publications' 'pune'
 'purushottam' 'pushed' 'qualified' 'qualitative' 'quality' 'quantitative'
 'quizzes' 'racing' 'rajkumar' 'rama' 'reach' 'real' 'received'
 'recognized' 'record' 'recruitment' 'regular' 'relevant' 'repute'
 'reputed' 'research' 'responsibilities' 'responsible' 'result' 'results'
 'rewarding' 'robocon' 'salary' 'savitribai' 'scenario' 'science'
 'scientists' 'sctr' 'secretary' 'secured' 'securing' 'selected' 'self'
 'semester' 'seminars' 'service' 'sgpa' 'sharpen' 'showing' 'sic'
 'significant' 'significantly' 'sigs' 'singing' 'sir' 'skills' 'smart'
 'social' 'societies' 'society' 'software' 'solidarity' 'sought'
 'spacious' 'special' 'spirit' 'sports' 'sppu' 'staff' 'stakeholders'
 'stalked' 'start' 'startup' 'state' 'stimulating' 'strives' 'strong'
 'student' 'students' 'study' 'succeed' 'success' 'summits' 'support'
 'supported' 'supportive' 'sustainable' 'swastik' 'symposia' 'synergetic'
 'talent' 'talented' 'talents' 'tc' 'teaching' 'team' 'teamwork'
 'technical' 'technically' 'technocratic' 'technology' 'tedx'
 'telecommunication' 'thank' 'theodore' 'thinking' 'time' 'track'
 'transform' 'true' 'trustee' 'undergraduate' 'undertaken' 'undoubtedly'
 'university' 'untiring' 'value' 'values' 'various' 'versions' 'vibrant'
 'visionaries' 'visionary' 'visit' 'visits' 'von' 'way' 'welcome'
 'welcoming' 'wellbeing' 'wireless' 'wish' 'wishes' 'wonderful' 'work'
 'workshops' 'world' 'year' 'years' 'young']

TF-IDF Matrix:
 [[0.         0.         0.         0.         0.0325299  0.
  0.04571965 0.         0.         0.         0.         0.04571965
  0.04571965 0.06505981 0.         0.09143929 0.09143929 0.
  0.         0.         0.         0.04571965 0.0325299  0.
  0.         0.         0.0325299  0.04571965 0.0325299  0.
  0.         0.         0.0325299  0.         0.         0.04571965
  0.0325299  0.04571965 0.04571965 0.         0.04571965 0.
  0.04571965 0.         0.04571965 0.         0.         0.
  0.0325299  0.04571965 0.0325299  0.04571965 0.         0.
  0.04571965 0.         0.04571965 0.         0.04571965 0.
  0.         0.06505981 0.         0.         0.         0.04571965
  0.09143929 0.         0.06505981 0.         0.         0.04571965
  0.04571965 0.         0.         0.         0.         0.
  0.0325299  0.         0.         0.         0.0325299  0.
  0.04571965 0.         0.04571965 0.0325299  0.         0.04571965
  0.09758971 0.04571965 0.04571965 0.04571965 0.         0.
  0.0325299  0.04571965 0.         0.         0.04571965 0.
  0.         0.         0.09143929 0.         0.         0.
  0.         0.         0.0325299  0.0325299  0.         0.
  0.06505981 0.         0.         0.         0.04571965 0.
  0.         0.04571965 0.         0.04571965 0.04571965 0.
  0.09758971 0.04571965 0.09143929 0.         0.         0.
  0.04571965 0.04571965 0.         0.         0.04571965 0.
  0.         0.04571965 0.         0.         0.04571965 0.0325299
  0.         0.04571965 0.09758971 0.04571965 0.         0.
  0.         0.         0.         0.06505981 0.04571965 0.09143929
  0.         0.         0.06505981 0.         0.06505981 0.
  0.         0.         0.         0.0325299  0.         0.04571965
  0.04571965 0.         0.         0.         0.09143929 0.06505981
  0.         0.         0.04571965 0.04571965 0.04571965 0.
  0.04571965 0.06505981 0.         0.09758971 0.         0.06505981
  0.         0.04571965 0.         0.         0.         0.
  0.         0.         0.04571965 0.04571965 0.04571965 0.04571965
  0.0325299  0.         0.04571965 0.0325299  0.04571965 0.
  0.04571965 0.04571965 0.04571965 0.         0.04571965 0.0325299
  0.04571965 0.04571965 0.04571965 0.0325299  0.0325299  0.09143929
  0.         0.04571965 0.         0.         0.04571965 0.04571965
  0.         0.         0.         0.         0.04571965 0.
  0.         0.         0.         0.         0.         0.
  0.04571965 0.04571965 0.         0.         0.         0.
  0.04571965 0.         0.         0.0325299  0.06505981 0.
  0.04571965 0.04571965 0.         0.0325299  0.         0.04571965
  0.16264952 0.09143929 0.         0.         0.         0.0325299
  0.04571965 0.         0.04571965 0.04571965 0.04571965 0.04571965
  0.         0.09143929 0.         0.04571965 0.         0.
  0.0325299  0.04571965 0.04571965 0.04571965 0.         0.04571965
  0.04571965 0.04571965 0.         0.06505981 0.         0.
  0.04571965 0.         0.04571965 0.0325299  0.         0.
  0.         0.         0.         0.09143929 0.04571965 0.04571965
  0.04571965 0.04571965 0.         0.         0.         0.0325299
  0.         0.13011962 0.         0.         0.         0.04571965
  0.18287858 0.04571965 0.         0.04571965 0.06505981 0.04571965
  0.         0.         0.         0.         0.         0.
  0.         0.04571965 0.04571965 0.0325299  0.         0.06505981
  0.         0.04571965 0.04571965 0.04571965 0.         0.06505981
  0.         0.         0.         0.         0.04571965 0.
  0.         0.         0.         0.         0.0325299  0.45541866
  0.04571965 0.         0.06505981 0.04571965 0.04571965 0.
  0.0325299  0.         0.04571965 0.04571965 0.04571965 0.
  0.         0.         0.0325299  0.         0.0325299  0.04571965
  0.         0.         0.04571965 0.04571965 0.0325299  0.
  0.04571965 0.         0.         0.04571965 0.         0.09758971
  0.         0.         0.04571965 0.04571965 0.0325299  0.04571965
  0.         0.         0.04571965 0.04571965 0.         0.04571965
  0.         0.0325299  0.06505981 0.         0.         0.
  0.         0.04571965 0.13011962 0.         0.         0.
  0.         0.0325299  0.         0.         0.0325299  0.
  0.         0.04571965 0.04571965 0.04571965 0.         0.
  0.         0.04571965 0.         0.         0.         0.
  0.04571965 0.         0.         0.         0.         0.
  0.         0.04571965 0.         0.04571965 0.         0.
  0.         0.         0.         0.0325299  0.04571965 0.04571965
  0.04571965 0.         0.         0.         0.         0.04571965
  0.04571965 0.         0.13715894 0.         0.04571965 0.04571965
  0.09758971 0.09758971 0.04571965 0.         0.04571965 0.
  0.         0.         0.04571965 0.         0.04571965 0.
  0.04571965 0.         0.         0.         0.09143929 0.
  0.13715894 0.         0.0325299  0.         0.         0.06505981
  0.         0.         0.         0.04571965 0.         0.04571965
  0.04571965 0.         0.         0.04571965 0.13715894 0.
  0.04571965 0.0325299  0.04571965 0.         0.0325299  0.09143929
  0.04571965 0.         0.04571965 0.0325299  0.0325299  0.
  0.04571965 0.         0.04571965 0.04571965 0.04571965 0.
  0.0325299  0.         0.04571965 0.0325299  0.         0.13011962
  0.         0.         0.13011962]
 [0.10861249 0.07240833 0.03620416 0.03620416 0.02575956 0.03620416
  0.         0.03620416 0.03620416 0.03620416 0.03620416 0.
  0.         0.05151912 0.03620416 0.         0.         0.03620416
  0.03620416 0.03620416 0.03620416 0.         0.07727868 0.03620416
  0.03620416 0.03620416 0.02575956 0.         0.02575956 0.03620416
  0.03620416 0.03620416 0.02575956 0.03620416 0.03620416 0.
  0.05151912 0.         0.         0.03620416 0.         0.03620416
  0.         0.03620416 0.         0.03620416 0.03620416 0.03620416
  0.02575956 0.         0.07727868 0.         0.03620416 0.03620416
  0.         0.03620416 0.         0.03620416 0.         0.03620416
  0.03620416 0.10303824 0.03620416 0.03620416 0.03620416 0.
  0.         0.03620416 0.05151912 0.03620416 0.03620416 0.
  0.         0.03620416 0.10861249 0.03620416 0.03620416 0.03620416
  0.02575956 0.03620416 0.03620416 0.03620416 0.05151912 0.03620416
  0.         0.03620416 0.         0.02575956 0.03620416 0.
  0.1287978  0.         0.         0.         0.03620416 0.03620416
  0.02575956 0.         0.03620416 0.03620416 0.         0.03620416
  0.03620416 0.03620416 0.         0.07240833 0.03620416 0.03620416
  0.03620416 0.03620416 0.05151912 0.05151912 0.03620416 0.03620416
  0.05151912 0.03620416 0.03620416 0.03620416 0.         0.07240833
  0.03620416 0.         0.03620416 0.         0.         0.03620416
  0.07727868 0.         0.         0.03620416 0.03620416 0.03620416
  0.         0.         0.03620416 0.03620416 0.         0.03620416
  0.03620416 0.         0.03620416 0.03620416 0.         0.02575956
  0.03620416 0.         0.07727868 0.         0.03620416 0.10861249
  0.03620416 0.03620416 0.03620416 0.20607648 0.         0.
  0.03620416 0.07240833 0.02575956 0.03620416 0.02575956 0.07240833
  0.03620416 0.03620416 0.03620416 0.02575956 0.03620416 0.
  0.         0.07240833 0.07240833 0.03620416 0.         0.02575956
  0.03620416 0.03620416 0.         0.         0.         0.03620416
  0.         0.02575956 0.03620416 0.07727868 0.03620416 0.02575956
  0.03620416 0.         0.03620416 0.03620416 0.03620416 0.03620416
  0.03620416 0.03620416 0.         0.         0.         0.
  0.02575956 0.03620416 0.         0.02575956 0.         0.03620416
  0.         0.         0.         0.03620416 0.         0.05151912
  0.         0.         0.         0.02575956 0.05151912 0.
  0.03620416 0.         0.03620416 0.03620416 0.         0.
  0.03620416 0.03620416 0.03620416 0.03620416 0.         0.03620416
  0.03620416 0.03620416 0.03620416 0.03620416 0.03620416 0.03620416
  0.         0.         0.03620416 0.03620416 0.03620416 0.07240833
  0.         0.03620416 0.03620416 0.02575956 0.07727868 0.07240833
  0.         0.         0.03620416 0.02575956 0.03620416 0.
  0.10303824 0.         0.07240833 0.03620416 0.03620416 0.02575956
  0.         0.07240833 0.         0.         0.         0.
  0.03620416 0.         0.07240833 0.         0.03620416 0.10861249
  0.02575956 0.         0.         0.         0.03620416 0.
  0.         0.         0.03620416 0.05151912 0.03620416 0.03620416
  0.         0.07240833 0.         0.07727868 0.03620416 0.03620416
  0.03620416 0.03620416 0.03620416 0.         0.         0.
  0.         0.         0.03620416 0.03620416 0.03620416 0.02575956
  0.03620416 0.02575956 0.03620416 0.03620416 0.03620416 0.
  0.         0.         0.03620416 0.         0.02575956 0.
  0.03620416 0.07240833 0.03620416 0.03620416 0.03620416 0.03620416
  0.03620416 0.         0.         0.02575956 0.03620416 0.02575956
  0.10861249 0.         0.         0.         0.07240833 0.02575956
  0.03620416 0.03620416 0.03620416 0.03620416 0.         0.03620416
  0.03620416 0.03620416 0.03620416 0.03620416 0.05151912 0.36063384
  0.         0.03620416 0.02575956 0.         0.         0.07240833
  0.02575956 0.03620416 0.         0.         0.         0.03620416
  0.03620416 0.03620416 0.05151912 0.03620416 0.07727868 0.
  0.03620416 0.03620416 0.         0.         0.05151912 0.03620416
  0.         0.03620416 0.07240833 0.         0.03620416 0.07727868
  0.03620416 0.03620416 0.         0.         0.05151912 0.
  0.03620416 0.03620416 0.         0.         0.03620416 0.
  0.03620416 0.02575956 0.02575956 0.03620416 0.03620416 0.03620416
  0.03620416 0.         0.18031692 0.03620416 0.03620416 0.03620416
  0.03620416 0.02575956 0.07240833 0.03620416 0.05151912 0.03620416
  0.03620416 0.         0.         0.         0.03620416 0.03620416
  0.03620416 0.         0.03620416 0.03620416 0.07240833 0.03620416
  0.         0.03620416 0.03620416 0.03620416 0.03620416 0.03620416
  0.03620416 0.         0.10861249 0.         0.03620416 0.03620416
  0.03620416 0.03620416 0.03620416 0.02575956 0.         0.
  0.         0.07240833 0.10861249 0.07240833 0.03620416 0.
  0.         0.03620416 0.         0.03620416 0.         0.
  0.1287978  0.23183604 0.         0.03620416 0.         0.03620416
  0.03620416 0.03620416 0.         0.03620416 0.         0.03620416
  0.         0.03620416 0.03620416 0.03620416 0.         0.03620416
  0.         0.03620416 0.07727868 0.03620416 0.03620416 0.15455736
  0.03620416 0.10861249 0.03620416 0.         0.10861249 0.
  0.         0.03620416 0.03620416 0.         0.         0.03620416
  0.         0.05151912 0.         0.03620416 0.05151912 0.
  0.         0.03620416 0.         0.02575956 0.02575956 0.03620416
  0.         0.03620416 0.         0.         0.         0.03620416
  0.02575956 0.03620416 0.         0.05151912 0.03620416 0.02575956
  0.07240833 0.03620416 0.02575956]]

In [14]:
import pandas as pd

df = pd.DataFrame(tfidf_matrix.toarray(), columns=feature_names)

pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)
df

,10,100,12,19,1983,1st,2015,240,326,3500,41,9001,academia,academic,accomplishments,accreditation,accredited,achievements,achievers,achieving,acm,actively,activities,acumen,adapting,additionally,affiliated,agencies,ahead,aicte,alongside,ambassadors,ambitions,annual,appreciate,aptitudes,art,aspiring,assessment,assure,atmosphere,attitude,attitudes,automobile,avenues,average,awards,bagged,based,beginning,best,better,betterment,big,board,brand,bridge,bright,buddy,buddys,building,campus,career,carnivals,cart,caters,ce,celebrate,cell,center,centered,centres,certified,challenges,challenging,chosen,circle,close,clubs,college,colleges,combination,come,commendable,committed,communication,community,companies,competition,competitiveness,computer,concepts,confident,consistently,constant,constitute,consultancy,continue,continuous,contributing,council,country,course,covid,create,creates,creativity,critical,crore,csi,cultural,culture,cup,current,curricular,cut,dance,data,dear,debate,decades,dedicated,demands,department,desirous,despite,development,directed,director,disruption,distinction,distinctions,diverse,dr,drama,drdo,dream,dreams,drive,drives,drone,dst,dte,ecosystem,edc,educate,education,efforts,electric,electronics,empower,encourages,engineer,engineering,engineers,ensures,entering,enterprising,entire,entrepreneurial,entrepreneurship,environment,equal,equip,equipped,established,ethical,ethics,event,events,examination,excel,excellence,excellent,exciting,expand,experience,experienced,exposure,extend,extends,extra,extraordinary,faculty,fairs,family,fe,fetched,field,fierce,final,finally,finding,firodiya,flagship,focused,founder,fraternity,friends,funded,funding,future,gap,getting,gives,going,gopalkrishnan,got,graded,graduate,grants,great,green,group,groups,growth,hackathons,hard,heartening,help,helped,helping,higher,highest,holistic,houses,hub,ict,ideas,ieee,iet,illustrious,imagine,imbibed,immense,impetus,important,include,increased,inculcate,inculcating,india,individuals,industrial,industry,information,infrastructure,ingenious,innovate,innovation,innovative,inspiring,institute,institution,institutions,integral,intense,interaction,interests,international,internship,introducing,involved,iso,job,journey,karandak,karman,know,knowledge,known,kothavale,krishnan,laboratories,lakh,late,lead,leaders,leading,learning,let,levels,library,life,lifetime,like,limited,local,long,lot,lpa,maharashtra,make,makes,management,managing,marched,medals,meet,members,microsoft,minds,mission,model,modern,moulding,mr,multinational,mun,naac,national,nba,neglecting,new,niche,normal,notch,nourishes,number,numerous,nurture,offers,online,opportunities,opportunity,ordinary,outstanding,overall,package,participation,partners,pass,past,patents,peaceful,peers,percentage,period,periodic,person,phule,pict,pioneer,pioneering,placement,pleasure,popularly,position,post,potential,preferred,premier,preparing,prestigious,pride,prizes,product,profession,professional,professionalism,professionals,professors,program,programmes,programs,projects,promotive,provide,provides,providing,publications,pune,purushottam,pushed,qualified,qualitative,quality,quantitative,quizzes,racing,rajkumar,rama,reach,real,received,recognized,record,recruitment,regular,relevant,repute,reputed,research,responsibilities,responsible,result,results,rewarding,robocon,salary,savitribai,scenario,science,scientists,sctr,secretary,secured,securing,selected,self,semester,seminars,service,sgpa,sharpen,showing,sic,significant,significantly,sigs,singing,sir,skills,smart,social,societies,society,software,solidarity,sought,spacious,special,spirit,sports,sppu,staff,stakeholders,stalked,start,startup,state,stimulating,strives,strong,student,students,study,succeed,success,summits,support,supported,supportive,sustainable,swastik,symposia,synergetic,talent,talented,talents,tc,teaching,team,teamwork,technical,technically,technocratic,technology,tedx,telecommunication,thank,theodore,thinking,time,track,transform,true,trustee,undergraduate,undertaken,undoubtedly,university,untiring,value,values,various,versions,vibrant,visionaries,visionary,visit,visits,von,way,welcome,welcoming,wellbeing,wireless,wish,wishes,wonderful,work,workshops,world,year,years,young
0,0.000000,0.000000,0.000000,0.000000,0.03253,0.000000,0.04572,0.000000,0.000000,0.000000,0.000000,0.04572,0.04572,0.065060,0.000000,0.091439,0.091439,0.000000,0.000000,0.000000,0.000000,0.04572,0.032530,0.000000,0.000000,0.000000,0.03253,0.04572,0.03253,0.000000,0.000000,0.000000,0.03253,0.000000,0.000000,0.04572,0.032530,0.04572,0.04572,0.000000,0.04572,0.000000,0.04572,0.000000,0.04572,0.000000,0.000000,0.000000,0.03253,0.04572,0.032530,0.04572,0.000000,0.000000,0.04572,0.000000,0.04572,0.000000,0.04572,0.000000,0.000000,0.065060,0.000000,0.000000,0.000000,0.04572,0.091439,0.000000,0.065060,0.000000,0.000000,0.04572,0.04572,0.000000,0.000000,0.000000,0.000000,0.000000,0.03253,0.000000,0.000000,0.000000,0.032530,0.000000,0.04572,0.000000,0.04572,0.03253,0.000000,0.04572,0.097590,0.04572,0.04572,0.04572,0.000000,0.000000,0.03253,0.04572,0.000000,0.000000,0.04572,0.000000,0.000000,0.000000,0.091439,0.000000,0.000000,0.000000,0.000000,0.000000,0.032530,0.032530,0.000000,0.000000,0.065060,0.000000,0.000000,0.000000,0.04572,0.000000,0.000000,0.04572,0.000000,0.04572,0.04572,0.000000,0.097590,0.04572,0.091439,0.000000,0.000000,0.000000,0.04572,0.04572,0.000000,0.000000,0.04572,0.000000,0.000000,0.04572,0.000000,0.000000,0.04572,0.03253,0.000000,0.04572,0.097590,0.04572,0.000000,0.000000,0.000000,0.000000,0.000000,0.065060,0.04572,0.091439,0.000000,0.000000,0.06506,0.000000,0.06506,0.000000,0.000000,0.000000,0.000000,0.03253,0.000000,0.04572,0.04572,0.000000,0.000000,0.000000,0.091439,0.06506,0.000000,0.000000,0.04572,0.04572,0.04572,0.000000,0.04572,0.06506,0.000000,0.097590,0.000000,0.06506,0.000000,0.04572,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.04572,0.04572,0.04572,0.04572,0.03253,0.000000,0.04572,0.03253,0.04572,0.000000,0.04572,0.04572,0.04572,0.000000,0.04572,0.032530,0.04572,0.04572,0.04572,0.03253,0.032530,0.091439,0.000000,0.04572,0.000000,0.000000,0.04572,0.04572,0.000000,0.000000,0.000000,0.000000,0.04572,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.04572,0.04572,0.000000,0.000000,0.000000,0.000000,0.04572,0.000000,0.000000,0.03253,0.065060,0.000000,0.04572,0.04572,0.000000,0.03253,0.000000,0.04572,0.162650,0.091439,0.000000,0.000000,0.000000,0.03253,0.04572,0.000000,0.04572,0.04572,0.04572,0.04572,0.000000,0.091439,0.000000,0.04572,0.000000,0.000000,0.03253,0.04572,0.04572,0.04572,0.000000,0.04572,0.04572,0.04572,0.000000,0.065060,0.000000,0.000000,0.04572,0.000000,0.04572,0.032530,0.000000,0.000000,0.000000,0.000000,0.000000,0.091439,0.04572,0.04572,0.04572,0.04572,0.000000,0.000000,0.000000,0.03253,0.000000,0.13012,0.000000,0.000000,0.000000,0.04572,0.182879,0.04572,0.000000,0.04572,0.06506,0.04572,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.04572,0.04572,0.03253,0.000000,0.06506,0.000000,0.04572,0.04572,0.04572,0.000000,0.06506,0.000000,0.000000,0.000000,0.000000,0.04572,0.000000,0.000000,0.000000,0.000000,0.000000,0.032530,0.455419,0.04572,0.000000,0.06506,0.04572,0.04572,0.000000,0.03253,0.000000,0.04572,0.04572,0.04572,0.000000,0.000000,0.000000,0.032530,0.000000,0.032530,0.04572,0.000000,0.000000,0.04572,0.04572,0.032530,0.000000,0.04572,0.000000,0.000000,0.04572,0.000000,0.097590,0.000000,0.000000,0.04572,0.04572,0.032530,0.04572,0.000000,0.000000,0.04572,0.04572,0.000000,0.04572,0.000000,0.03253,0.06506,0.000000,0.000000,0.000000,0.000000,0.04572,0.130120,0.000000,0.000000,0.000000,0.000000,0.03253,0.000000,0.000000,0.032530,0.000000,0.000000,0.04572,0.04572,0.04572,0.000000,0.000000,0.000000,0.04572,0.000000,0.000000,0.000000,0.000000,0.04572,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.04572,0.000000,0.04572,0.000000,0.000000,0.000000,0.000000,0.000000,0.03253,0.04572,0.04572,0.04572,0.000000,0.000000,0.000000,0.000000,0.04572,0.04572,0.000000,0.137159,0.000000,0.04572,0.04572,0.097590,0.097590,0.04572,0.000000,0.04572,0.000000,0.000000,0.000000,0.04572,0.000000,0.04572,0.000000,0.04572,0.000000,0.000000,0.000000,0.091439,0.000000,0.137159,0.000000,0.032530,0.000000,0.000000,0.065060,0.000000,0.000000,0.000000,0.04572,0.000000,0.04572,0.04572,0.000000,0.000000,0.04572,0.137159,0.000000,0.04572,0.032530,0.04572,0.000000,0.032530,0.091439,0.04572,0.000000,0.04572,0.03253,0.03253,0.000000,0.04572,0.000000,0.04572,0.04572,0.04572,0.000000,0.03253,0.000000,0.04572,0.032530,0.000000,0.13012,0.000000,0.000000,0.13012
1,0.108612,0.072408,0.036204,0.036204,0.02576,0.036204,0.00000,0.036204,0.036204,0.036204,0.036204,0.00000,0.00000,0.051519,0.036204,0.000000,0.000000,0.036204,0.036204,0.036204,0.036204,0.00000,0.077279,0.036204,0.036204,0.036204,0.02576,0.00000,0.02576,0.036204,0.036204,0.036204,0.02576,0.036204,0.036204,0.00000,0.051519,0.00000,0.00000,0.036204,0.00000,0.036204,0.00000,0.036204,0.00000,0.036204,0.036204,0.036204,0.02576,0.00000,0.077279,0.00000,0.036204,0.036204,0.00000,0.036204,0.00000,0.036204,0.00000,0.036204,0.036204,0.103038,0.036204,0.036204,0.036204,0.00000,0.000000,0.036204,0.051519,0.036204,0.036204,0.00000,0.00000,0.036204,0.108612,0.036204,0.036204,0.036204,0.02576,0.036204,0.036204,0.036204,0.051519,0.036204,0.00000,0.036204,0.00000,0.02576,0.036204,0.00000,0.128798,0.00000,0.00000,0.00000,0.036204,0.036204,0.02576,0.00000,0.036204,0.036204,0.00000,0.036204,0.036204,0.036204,0.000000,0.072408,0.036204,0.036204,0.036204,0.036204,0.051519,0.051519,0.036204,0.036204,0.051519,0.036204,0.036204,0.036204,0.00000,0.072408,0.036204,0.00000,0.036204,0.00000,0.00000,0.036204,0.077279,0.00000,0.000000,0.036204,0.036204,0.036204,0.00000,0.00000,0.036204,0.036204,0.00000,0.036204,0.036204,0.00000,0.036204,0.036204,0.00000,0.02576,0.036204,0.00000,0.077279,0.00000,0.036204,0.108612,0.036204,0.036204,0.036204,0.206076,0.00000,0.000000,0.036204,0.072408,0.02576,0.036204,0.02576,0.072408,0.036204,0.036204,0.036204,0.02576,0.036204,0.00000,0.00000,0.072408,0.072408,0.036204,0.000000,0.02576,0.036204,0.036204,0.00000,0.00000,0.00000,0.036204,0.00000,0.02576,0.036204,0.077279,0.036204,0.02576,0.036204,0.00000,0.036204,0.036204,0.036204,0.036204,0.036204,0.036204,0.00000,0.00000,0.00000,0.00000,0.02576,0.036204,0.00000,0.02576,0.00000,0.036204,0.00000,0.00000,0.00000,0.036204,0.00000,0.051519,0.00000,0.00000,0.00000,0.02576,0.051519,0.000000,0.036204,0.00000,0.036204,0.036204,0.00000,0.00000,0.036204,0.036204,0.036204,0.036204,0.00000,0.036204,0.036204,0.036204,0.036204,0.036204,0.036204,0.036204,0.00000,0.00000,0.036204,0.036204,0.036204,0.072408,0.00000,0.036204,0.036204,0.02576,0.077279,0.072408,0.00000,0.00000,0.036204,0.02576,0.036204,0.00000,0.103038,0.000000,0.072408,0.036204,0.036204,0.02576,0.00000,0.072408,0.00000,0.00000,0.00000,0.00000,0.036204,0.000000,0.072408,0.00000,0.036204,0.108612,0.02576,0.00000,0.00000,0.00000,0.036204,0.00000,0.00000,0.00000,0.036204,0.051519,0.036204,0.036204,0.00000,0.072408,0.00000,0.077279,0.036204,0.036204,0.036204,0.036204,0.036204,0.000000,0.00000,0.00000,0.00000,0.00000,0.036204,0.036204,0.036204,0.02576,0.036204,0.02576,0.036204,0.036204,0.036204,0.00000,0.000000,0.00000,0.036204,0.00000,0.02576,0.00000,0.036204,0.072408,0.036204,0.036204,0.036204,0.036204,0.036204,0.00000,0.00000,0.02576,0.036204,0.02576,0.108612,0.00000,0.00000,0.00000,0.072408,0.02576,0.036204,0.036204,0.036204,0.036204,0.00000,0.036204,0.036204,0.036204,0.036204,0.036204,0.051519,0.360634,0.00000,0.036204,0.02576,0.00000,0.00000,0.072408,0.02576,0.036204,0.00000,0.00000,0.00000,0.036204,0.036204,0.036204,0.051519,0.036204,0.077279,0.00000,0.036204,0.036204,0.00000,0.00000,0.051519,0.036204,0.00000,0.036204,0.072408,0.00000,0.036204,0.077279,0.036204,0.036204,0.00000,0.00000,0.051519,0.00000,0.036204,0.036204,0.00000,0.00000,0.036204,0.00000,0.036204,0.02576,0.02576,0.036204,0.036204,0.036204,0.036204,0.00000,0.180317,0.036204,0.036204,0.036204,0.036204,0.02576,0.072408,0.036204,0.051519,0.036204,0.036204,0.00000,0.00000,0.00000,0.036204,0.036204,0.036204,0.00000,0.036204,0.036204,0.072408,0.036204,0.00000,0.036204,0.036204,0.036204,0.036204,0.036204,0.036204,0.00000,0.108612,0.00000,0.036204,0.036204,0.036204,0.036204,0.036204,0.02576,0.00000,0.00000,0.00000,0.072408,0.108612,0.072408,0.036204,0.00000,0.00000,0.036204,0.000000,0.036204,0.00000,0.00000,0.128798,0.231836,0.00000,0.036204,0.00000,0.036204,0.036204,0.036204,0.00000,0.036204,0.00000,0.036204,0.00000,0.036204,0.036204,0.036204,0.000000,0.036204,0.000000,0.036204,0.077279,0.036204,0.036204,0.154557,0.036204,0.108612,0.036204,0.00000,0.108612,0.00000,0.00000,0.036204,0.036204,0.00000,0.000000,0.036204,0.00000,0.051519,0.00000,0.036204,0.051519,0.000000,0.00000,0.036204,0.00000,0.02576,0.02576,0.036204,0.00000,0.036204,0.00000,0.00000,0.00000,0.036204,0.02576,0.036204,0.00000,0.051519,0.036204,0.02576,0.072408,0.036204,0.02576

In [15]:
# Show top 10 words as a table
for i in range(len(df)):
    print(f"\nTop words in Document {i+1}:\n")
    display(df.iloc[i].sort_values(ascending=False).head(10).to_frame(name="TF-IDF Score"))

Top words in Document 1:

               TF-IDF Score
pict               0.455419
mr                 0.182879
institute          0.162650
team               0.137159
undergraduate      0.137159
state              0.137159
world              0.130120
young              0.130120
minds              0.130120
research           0.130120

Top words in Document 2:

             TF-IDF Score
pict             0.360634
students         0.231836
engineering      0.206076
research         0.180317
technology       0.154557
student          0.128798
computer         0.128798
10               0.108612
knowledge        0.108612
skills           0.108612